# Setup env
FROM node:10-buster-slim
RUN mkdir -p /app
WORKDIR /app
RUN apt update
# For deasync@0.1.14
RUN apt install -y python build-essential

# Setup app
COPY package.json .
COPY package-lock.json .
RUN npm install

# Add app
COPY src src

# Run app
CMD npm run dev