apiVersion: skaffold/v1beta16
kind: Config
metadata:
  name: task-timer
profiles:
  - name: task-timer-dev
    build:
      artifacts:
        - image: registry.gitlab.com/pojntfx/pojntfx/task-timer-dev
          docker:
            dockerfile: Dockerfile.dev
          sync:
            infer:
              - "**/*.js"
              - "**/*.html"
    deploy:
      kubectl:
        manifests:
          - stack.dev.yaml
  - name: task-timer-amd64
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:latest-amd64"
      artifacts:
        - image: registry.gitlab.com/pojntfx/pojntfx/task-timer
          docker:
            dockerfile: Dockerfile.amd64
    deploy:
      kubectl:
        manifests:
          - stack.yaml
  - name: task-timer-arm64
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:latest-arm64"
      artifacts:
        - image: registry.gitlab.com/pojntfx/pojntfx/task-timer
          docker:
            dockerfile: Dockerfile.arm64
    deploy:
      kubectl:
        manifests:
          - stack.yaml
