apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-timer
spec:
  selector:
    matchLabels:
      app: task-timer
  template:
    metadata:
      labels:
        app: task-timer
    spec:
      containers:
        - name: task-timer
          image: registry.gitlab.com/pojntfx/pojntfx/task-timer:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: task-timer
spec:
  selector:
    app: task-timer
  ports:
    - name: frontend
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: task-timer
spec:
  rules:
    - host: task-timer.felicitas.pojtinger.space
      http:
        paths:
          - path: /
            backend:
              serviceName: task-timer
              servicePort: frontend
