apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-timer-dev-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-timer-dev
spec:
  selector:
    matchLabels:
      app: task-timer-dev
  template:
    metadata:
      labels:
        app: task-timer-dev
    spec:
      containers:
        - name: task-timer-dev
          image: registry.gitlab.com/pojntfx/pojntfx/task-timer-dev
          ports:
            - containerPort: 1234
            - containerPort: 1235
          volumeMounts:
            - name: task-timer-dev-cache
              mountPath: /app/.cache
      volumes:
        - name: task-timer-dev-cache
          persistentVolumeClaim:
            claimName: task-timer-dev-cache

---
apiVersion: v1
kind: Service
metadata:
  name: task-timer-dev
spec:
  selector:
    app: task-timer-dev
  ports:
    - port: 1234
      targetPort: 1234
      name: http
    - port: 1235
      targetPort: 1235
      name: ws
