{{ if .Values.dev }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-timer-dev-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi

---
{{ end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-timer{{ if .Values.dev }}-dev{{ end }}
spec:
  selector:
    matchLabels:
      app: task-timer{{ if .Values.dev }}-dev{{ end }}
  template:
    metadata:
      labels:
        app: task-timer{{ if .Values.dev }}-dev{{ end }}
    spec:
      containers:
        - name: task-timer{{ if .Values.dev }}-dev{{ end }}
          image: {{ .Values.image }}
          {{ if .Values.dev }}
          volumeMounts:
            - name: task-timer-dev-cache
              mountPath: /app/.cache
          {{ else }}
          resources:
            limits:
              memory: {{ .Values.memory }}
              cpu: {{ .Values.cpu }}
          {{ end }}
          ports:
          {{ if .Values.dev }}
            - containerPort: 1234
            - containerPort: 1235
          {{ else }}
            - containerPort: 8080
          {{ end }}
      {{ if .Values.dev }}
      volumes:
        - name: task-timer-dev-cache
          persistentVolumeClaim:
            claimName: task-timer-dev-cache
      {{ end }}

---
apiVersion: v1
kind: Service
metadata:
  name: task-timer{{ if .Values.dev }}-dev{{ end }}
spec:
  selector:
    app: task-timer{{ if .Values.dev }}-dev{{ end }}
  ports:
    {{ if .Values.dev }}
    - port: 1234
      targetPort: 1234
      name: http
    - port: 1235
      targetPort: 1235
      name: ws
    {{ else }}
    - name: http
      port: 80
      targetPort: 8080
    {{ end }}
{{ if not .Values.dev }}

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: task-timer
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: task-timer
              servicePort: http
{{ end }}
